modLoader = "javafml"
loaderVersion = "[31,)"
license = "LGPLv3"
issueTrackerURL = "https://github.com/AsOne2020/fabric-mod-template/issues"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
displayURL = "https://github.com/AsOne2020/fabric-mod-template"
authors = "As_One"
description = '''
Template for my fabric mods
'''
logoFile = "icon.png"

[[dependencies."${id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_dependency}"
ordering = "NONE"
side = "BOTH"
