modLoader = "javafml"
loaderVersion = "[1,)"
license = "LGPLv3"
issueTrackerURL = "https://github.com/AsOne2020/AutoTame/issues"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
displayURL = "https://modrinth.com/mod/AutoTame"
authors = "As_One"
description = '''
Automatically retries taming horse-like animals until successful, making taming in Minecraft easier.
'''
logoFile = "icon.png"

[[dependencies."${id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_dependency}"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "${id}.mixins.json"
